name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build

    - name: Build CMake
      run: cmake --build ${{ github.workspace }}/build

    - name: Test
      run: cmake --build ${{ github.workspace }}/build --target test
    
    - name: Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
    - name: Publishing
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build
          asset_name: bin
          asset_content_type: application/octet-stream
