name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build

    - name: Build CMake
      run: cmake --build ${{ github.workspace }}/build

    - name: Test
      run: cmake --build ${{ github.workspace }}/build --target test
    
    - name: Release
      uses: actions/create-release@v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        asset_name: try_gtests
        release_name: try_gtests
        tag: v1.0.0
        file: tasks
        overwrite: true
        file_glob: true
