name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure CMake
      run: cmake -B /build

    - name: Build CMake
      run: cmake --build /build

    - name: Test
      run: cmake --build /build --target test

    - name: Run
      run: |
        cd /build
        tests
