name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Configure CMake
      run: cmake -B /build

    - name: Build CMake
      run: cmake --build /build

    - name: Test
      run: cmake --build /build --target test

    - name: Run
      run: |
        cd /build
        tests
